# mqtt_workshop/docker-compose.yml

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1884:1884"
    volumes:
      # Mount our custom config file
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  sensor_simulator:
    build: ./sensor_simulator
    container_name: sensor_simulator
    depends_on:
      - mqtt_broker